# Copyright ¬©2017-2025  Mr MXF   info@mrmxf.com
# BSD-3-Clause License           https://opensource.org/license/bsd-3-clause/
# clogwork - collection of reusable actions and tools for Mr MXF project.
#
#   _                         _             _   _      _ 
#  | |_   __ _   __ _   ___  | |__   _  _  (_) | |  __| |
#  |  _| / _` | / _` | |___| | '_ \ | || | | | | | / _` |
#   \__| \__,_| \__, |       |_.__/  \_,_| |_| |_| \__,_|
#               |___/                                    
#
#  GitHub Workflow to build & deploy the metarex website
#
# Needs:
# -     vars.DOCKER_NS - the account namespace for docker hub e.g. mrmxf
# - secrets.DOCKER_PAT - the personal access token for pushing to docker hub
# - secrets.HOOK_SLACK - the SLACK WEBHOOK to post messages to the team
# - secrets.GET_CLOG   - the magic string for eval "$GET_CLOG" to install clog

name: tag-build-deploy
run-name: "ü•∑${{ github.actor }}: üèÉ‚Äç‚û°Ô∏è ${{ github.workflow }} @ ${{ github.event.repository.name }}:${{ github.ref_name }}"
on:
  create:                       # run when a tag is created
  workflow_dispatch:            # run manually from Actions tab

# Default to bash
defaults:
  run:
    shell: bash

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. Allow cancelling in-progress runs.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  # Build job
  build:
    uses: mrmxf/clogwork/.github/workflows/build-hugo.yaml@main
    with:
      artifact-name: kodata-www-metarex-media
      docker_ns: ${{ vars.DOCKER_NS }}
    secrets:
      docker_pat: ${{ secrets.DOCKER_PAT }}
      get_clog: ${{ secrets.GET_CLOG }}
      # provide a slack_webhook to get a slack message otherwise silence
      webhook_slack: ${{ secrets.HOOK_SLACK }}
      
  #dump properties of the build output / needs context
  dump-context:
    needs: [build]
    uses: mrmxf/clogwork/.github/workflows/dump-context.yaml@main
